# Class exercises - configuration for single class
---
classes:
  - exercises:
      # `file` is relative to .strigo directory
      - file: "../exercise-log-in-to-the-fme-academy/exercise.md"
        title: "Exercise: Log in to the FME Academy"
      - file: "../what-is-fme-server/exercise.md"
        title: "What is FME Server?"
      - file: "../fme-server-use-cases/exercise.md"
        title: "FME Server Use Cases"
      - file: "../fme-server-components/exercise.md"
        title: "FME Server Components"
      - file: "../connect-fme-workbench-to-fme-server/exercise.md"
        title: "Connect FME Workbench to FME Server"
      - file: "../exercise-publish-to-fme-server/exercise.md"
        title: "Exercise: Publish to FME server"
      - file: "../log-in-to-fme-server/exercise.md"
        title: "Log In to FME Server"
      - file: "../run-a-workspace-in-fme-server/exercise.md"
        title: "Run a Workspace in FME Server"
      - file: "../exercise-run-a-workspace-in-fme-server/exercise.md"
        title: "Exercise: Run a Workspace in FME Server"
      - file: "../share-content-in-fme-server/exercise.md"
        title: "Share Content In FME Server"
      - file: "../exercise-share-a-workspace/exercise.md"
        title: "Exercise: Share a Workspace"
      - file: "../create-basic-self-serve-workflows/exercise.md"
        title: "Create Basic Self-Serve Workflows"
      - file: "../configure-workflows-for-the-web/exercise.md"
        title: "Configure Workflows for the Web"
      - file: "../exercise-create-a-simple-self-serve-portal/exercise.md"
        title: "Exercise: Create a Simple Self-Serve Portal"
      - file: "../manage-source-data/exercise.md"
        title: "Manage Source Data"
      - file: "../publish-data-with-a-workspace/exercise.md"
        title: "Exercise: Publish Data with a Workspace"
      - file: "../use-temporary-uploads-for-end-users/exercise.md"
        title: "Use Temporary Uploads for End Users"
      - file: "../use-the-resource-file-system/exercise.md"
        title: "Use the Resource File System"
      - file: "../author-for-the-resources-system/exercise.md"
        title: "Author for the Resources System"
      - file: "../exercise-use-the-resource-file-system/exercise.md"
        title: "Exercise: Use the Resource File System"
      - file: "../use-database-and-web-connections/exercise.md"
        title: "Use Database and Web Connections"
      - file: "../design-user-controlled-workspaces/exercise.md"
        title: "Design User-Controlled Workspaces"
      - file: "../exercise-create-a-user-controlled-workspace/exercise.md"
        title: "Exercise: Create a User-Controlled Workspace"
      - file: "../exercise-reuse-user-parameters/exercise.md"
        title: "Exercise: Reuse User Parameters"
      - file: "../choose-the-correct-parameter-type/exercise.md"
        title: "Choose the Correct Parameter Type"
      - file: "../let-users-choose-a-geographic-area-of-interest/exercise.md"
        title: "Let Users Choose a Geographic Area of interest"
      - file: "../exercise-use-the-geometry-published-parameter/exercise.md"
        title: "Exercise: Use the Geometry Published Parameter"
      - file: "../share-workspaces-as-apps/exercise.md"
        title: "Share Workspaces as Apps"
      - file: "../exercise-create-an-fme-server-app/exercise.md"
        title: "Exercise: Create an FME Server App"
      - file: "../exercise-customize-an-fme-server-app/exercise.md"
        title: "Exercise: Customize an FME Server App"
      - file: "../use-gallery-apps/exercise.md"
        title: "Use Gallery Apps"
      - file: "../what-are-automations/exercise.md"
        title: "What are Automations?"
      - file: "../build-basic-automations/exercise.md"
        title: "Build Basic Automations"
      - file: "../exercise-build-a-basic-automation/exercise.md"
        title: "Exercise: Build A Basic Automation"
      - file: "../run-workspaces-with-directory-watch-triggers/exercise.md"
        title: "Run Workspaces with Directory Watch Triggers"
      - file: "../exercise-create-a-resources-network-directory-automation/exercise.md"
        title: "Exercise: Create a Resources or Network Directory Automation"
      - file: "../exercise-process-resource-or-network-directory-messages/exercise.md"
        title: "Exercise: Process Resource or Network Directory Messages"
      - file: "../run-workspaces-on-a-schedule/exercise.md"
        title: "Run Workspaces on a Schedule"
      - file: "../choose-smtp-or-imap-for-email-automations/exercise.md"
        title: "Choose SMTP or IMAP for Email Automations"
      - file: "../run-workspaces-with-email-triggers/exercise.md"
        title: "Run Workspaces with Email Triggers"
      - file: "../exercise-run-a-workspace-in-response-to-incoming-email/exercise.md"
        title: "Exercise: Run a Workspace in Response to Incoming Email"
      - file: "../connect-workspaces-in-automations/exercise.md"
        title: "Connect Workspaces in Automations"
      - file: "../use-the-automations-writer/exercise.md"
        title: "Use the Automations Writer"
      - file: "../exercise-use-the-automations-writer/exercise.md"
        title: "Exercise: Use the Automations Writer"
      - file: "../exercise-chain-multiple-jobs-in-an-automation/exercise.md"
        title: "Exercise: Chain Multiple Jobs in an Automation"
      - file: "../exercise-orchestrate-complex-jobs/exercise.md"
        title: "Exercise: Orchestrate Complex Jobs"
      - file: "../course-wrap-up/exercise.md"
        title: "Course Wrap Up"



# Class exercises - configuration for multiple classes
# ---
# classes:
#   # `class_id` may be omitted if there is only one class in this file
#   - class_id: "<your_class_id>"
#     exercises:
#       # `file` is relative to .strigo directory
#       - file: "../hello-world/hello.md"
#         title: "Hello!"
#       - file: "../hello-world/world.md"
#         title: "World!"
#   - class_id: "<your_class_id>"
#     exercises:
#       - file: "../markup-syntaxes/markdown.md"
#         title: "Markdown!"
#         # `syntax` is optional
#         # can be "md" | "rst"
#         # uses file extension as fallback
#         syntax: "md"
#       - file: "../markup-syntaxes/restructured.rst"
#         title: "Restructed"
#         syntax: "rst"
#   - class_id: "<your_class_id>"
#     exercises:
#       - file: "../relative-images/md-with-relative-imgs.md"
#         title: "Relative images"
