# Class exercises - configuration for single class
---
classes:
  - exercises:
      # `file` is relative to .strigo directory. Don't include number in title--that happens automatically.
      #In Atom, create the file and title here. Then edit the MD file.
      #Use https://euangoddard.github.io/clipboard2markdown/  to create the clipboard2markdown
      #Add <head><base target="_blank"> </head> to the top of the MD file.
      - file: "../read-data/exercise.md"
        title: "Read Data"
      - file: "../view-data/exercise.md"
        title: "View Data"
      - file: "../write-data/exercise.md"
        title: "Write Data"
      - file: "../multiple-streams/exercise.md"
        title: "Multiple Streams"
      - file: "../document-a-workspace/exercise.md"
        title: "Document A Workspace"
      - file: "../transform-data/exercise.md"
        title: "Transform Data"
      - file: "../publish-a-workspace/exercise.md"
        title: "Publish a Workspace"
      - file: "../automate-a-workspace/exercise.md"
        title: "Automate a Workspace"
