# Class exercises - configuration for single class
---
classes:
  - exercises:
      # `file` is relative to .strigo directory. Don't include number in title--that happens automatically
      - file: "../1-read-data/1-read-data.md"
        title: "Read Data"

