# Class exercises - configuration for single class
---
classes:
  - exercises:
      # `file` is relative to .strigo directory. Don't include number in title--that happens automatically.
      #In Atom, create the file and title here. Then edit the MD file.
      #Use https://euangoddard.github.io/clipboard2markdown/  to create the clipboard2markdown
      #Add <head><base target="_blank"> </head> to the top of the MD file.
      - file: "../read-and-view-data/exercise.md"
        title: "Read and View Data"
      - file: "../write-data-and-multiple-streams/exercise.md"
        title: "Write Data and Multiple Streams"      
      - file: "../document-a-workspace-and-transform-data/exercise.md"
        title: "Document A Workspace and Transform Data"
      - file: "../run-a-workspace-with-fme-server/exercise.md"
        title: "Run a Workspace with FME Server"
      - file: "../automate-a-workspace/exercise.md"
        title: "Automate a Workspace"
      - file: "../course-wrap-up/exercise.md"
        title: "Course Wrap Up"
