# Class exercises - configuration for single class
---
classes:
  - exercises:
      # `file` is relative to .strigo directory. Don't include number in title--that happens automatically.
      #In Atom, create the file and title here. Then edit the MD file.
      #Use https://euangoddard.github.io/clipboard2markdown/  to create the clipboard2markdown
      #Add <head><base target="_blank"> </head> to the top of the MD file.
      #Add Click "Next" to the end of each MD file. Add Click "Done" to the final MD file.
      # Use title ####. It's the best size.
      #Don't include numbers in titles; you'll just regret it later on.
      - file: "../log-in-to-academy/exercise.md"
        title: "Log In to the FME Academy"
      - file: "../open-workbench/exercise.md"
        title: "Open Workbench"

      - file: "../maximizing-the-value-of-data/exercise.md"
        title: "Maximizing the Value of Data"
      - file: "../who-uses-fme/exercise.md"
        title: "Who Uses FME?"
      - file: "../integrate-data-across-your-organization/exercise.md"
        title: "Integrate Data Across Your Organization"
      - file: "../get-help-learning-and-using-fme/exercise.md"
        title: "Get Help Learning and Using FME"
      - file: "../connect-and-view-data/exercise.md"
        title: "Connect and View Data"
      - file: "../write-data-basic-troubleshooting/exercise.md"
        title: "Write Data & Basic Troubleshooting"
      - file: "../bring-together-multiple-streams/exercise.md"
        title: "Bring Together Multiple Streams"
      - file: "../document-your-workspace/exercise.md"
        title: "Document Your Workspace"
      - file: "../view-data-with-a-background-map/exercise.md"
        title: "View Data with a Background Map"
      - file: "../interactively-view-spatial-data/exercise.md"
        title: "Interactively View Spatial Data"
      - file: "../view-data-as-a-table/exercise.md"
        title: "View Data as a Table"
      - file: "../view-information-about-a-specific-feature/exercise.md"
        title: "View Information About a Specific Feature"
      - file: "../interactively-view-3d-data/exercise.md"
        title: "Interactively View 3D Data"

      - file: "../quickly-create-a-conversion-workflow/exercise.md"
        title: "Quickly Create a Conversion Workflow"
      - file: "../edit-datas-schema/exercise.md"
        title: "Edit Data's Schema"
      - file: "../map-datas-schema/exercise.md"
        title: "Map Data's Schema"
      - file: "../author-and-debug-workspaces-efficiently/exercise.md"
        title: "Author and Debug Workspaces Efficiently"
      - file: "../find-the-right-transformer/exercise.md"
        title: "Find the Right Transformer"
      - file: "../filter-data-by-attribute-values/exercise.md"
        title: "Filter Data by Attribute Values"

      - file: "../create-and-modify-attributes/exercise.md"
        title: "Create and Modify Attributes"

      - file: "../use-conditional-filtering/exercise.md"
        title: "Use Conditional Filtering"
      - file: "../process-data-in-groups/exercise.md"
        title: "Process Data In Groups"

      - file: "../workspace-prototyping/exercise.md"
        title: "Workspace Prototyping"
      - file: "../use-multiple-readers-and-writers/exercise.md"
        title: "Use Multiple Readers and Writers"
      - file: "../use-partial-runs-to-test-your-workspace/exercise.md"
        title: "Use Partial Runs To Test Your Workspace"

      - file: "../flood-risk-project/exercise.md"
        title: "Flood Risk Project"

      - file: "../join-tables/exercise.md"
        title: "Join Tables"

      - file: "../join-tables/exercise.md"
        title: "Join Tables"

      - file: "../improving-workspace-style/exercise.md"
        title: "Improving Workspace Style"

      - file: "../debugging-a-workspace/exercise.md"
        title: "Debugging a Workspace"
      - file: "../investigate-problems-step-by-step-with-feature-debugging/exercise.md"
        title: "Investigate Problems Step-By-Step With Feature Debugging"
